#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Shogo Yamashita
import sys
import random


def shuffle(count):
    for i in range(count):
         rand_num[i] = random.randint(0, count // 2 - 1)
         if i % 2 == 0:
             out[rand_num[i-1]], out[rand_num[i]] = out[rand_num[i]], out[rand_num[i-1]]

    return out


# 行数を取得
inpt_list = []
out = []
count = 0

for line in sys.stdin:
    print(line.rstrip("\n"))
    count += 2
    inpt_list.append(line.rstrip("\n"))
    out.append(line.rstrip("\n"))

#print(count)
#print(out)
print("")

rand_num = [0] * count

if count // 2 > 1:
    while out == inpt_list:
        shuffle(count)


for i in range(count // 2):
    print(out[i])
