#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Shogo Yamashita
import sys
import random


# 標準入力の取得
inpt = sys.stdin.read()
print(inpt)

# 行数を取得
count = len(inpt)
out = []

for line in inpt:
    if line != "\n":
        out.append(line)

rand_num = [0] * count

for i in range(count):
    rand_num[i] = random.randint(0, count / 2 - 1)
    if i % 2 == 0:
       #print(f"rand_num{i}: {rand_num[i]}")
       out[rand_num[i-1]], out[rand_num[i]] = out[rand_num[i]], out[rand_num[i-1]]

#print("count: " ,count)
#print("rand_num: " ,rand_num)
#print(out)

for i in range(count // 2):
    print(out[i])
