#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Shogo Yamashita
# SPDX-License-Identifier: MIT

import sys
import random


# ランダムに入れ替えをする関数
def shuffle(out_list, c):
    for i in range(c * 2):
         index1 = random.randint(0, c - 1)
         index2 = random.randint(0, c - 1)
         if (i + 1) % 2 == 0:
             out_list[index1], out_list[index2] = out_list[index2], out_list[index1]

    return out_list


inpt = []
out = []
count = 0

# 標準入力を配列にする
for line in sys.stdin:
    count += 1
    inpt.append(line.rstrip("\n"))
    out.append(line.rstrip("\n"))

# 入力と出力を同一にしないための処理
if count > 1:
    while out == inpt:
        shuffle(out, count)

# 出力
for line in out:
    print(line)
